[package]
name = "dbg-info"
version = "0.1.0"
edition = "2018"
license = "BSD-2-Clause-Patent"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[features]
dwarf5 = []
all-formats = ["dwarf5"]
default-formats = ["dwarf5"]